-- PATCH
INSERT INTO PATCH (PESYEAR, DATAPACK, VERSION, SUBVERSION) VALUES(2019, 6, 1, 6);

-- POSITIONS
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(0, 'GK ', 'Goalkeeper');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(1, 'CB ', 'Centre Back');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(2, 'LB ', 'Left Back');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(3, 'RB ', 'Right Back');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(4, 'DMF', 'Defensive Midfielder');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(5, 'CMF', 'Centre Midfielder');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(6, 'LMF', 'Left Midfielder');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(7, 'RMF', 'Right Midfielder');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(8, 'AMF', 'Attacking Midfielder');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(9, 'LWF', 'Left Wing Forward');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(10, 'RWF', 'Right Wing Forward');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(11, 'SS ', 'Second Striker');
INSERT INTO FIELDPOSITION(ID, CODE, DESCRIPTION) VALUES(12, 'CF ', 'Centre Forward');
