SELECT * FROM ABILITY_LEVEL
SELECT * FROM POSITION_RATING
SELECT * FROM PLAYER_DETAIL
SELECT * FROM COMBINATION
SELECT * FROM NATIONALITY
SELECT * FROM REGION
SELECT * FROM LEAGUE
SELECT * FROM TEAM
SELECT * FROM PLAYING_STYLE
SELECT * FROM FIELDPOSITION
SELECT * FROM PLAYER 
SELECT * FROM PATCH 
SELECT * FROM SKILL


--BUG WHERE TEAMID WAS NOT SAVED
DELETE FROM ABILITY_LEVEL 
WHERE playerid IN (SELECT PLAYERID FROM PUBLIC.PLAYER_DETAIL  WHERE TEAMID  IS NULL)
DELETE FROM PLAYER_DETAIL WHERE teamid IS NULL

-- To Disconnect DB
shutdown 

--Spring SECURITY
SELECT email AS username, password, enabled FROM USERS WHERE email='miguel.cumbay@live.com'
SELECT u.email as username, a.authority from AUTHORITIES as a inner join USERS u on a.userid = u.id where u.email='miguel.cumbay@live.com'